import localFont from "next/font/local";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "../components/Header";



export const metadata = {
  title: "Movies-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Header >

        </Header>
        <main>{children}</main>
      </body>
    </html>
  );
}
